/* Local-only media editor. No network writes, no storage of API keys. ZIP uses STORE compression. */
(() => {
 'use strict';
 const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const products=[...MS_CONFIG.aircraft,...MS_CONFIG.products];
 const drafts=JSON.parse(JSON.stringify(window.MS_MEDIA_OVERRIDES||{})),files=new Map(),objectURLs=new Map();let serial=0;
 const supported={'image/png':'png','image/jpeg':'jpg','image/webp':'webp','image/gif':'gif','image/avif':'avif','video/mp4':'mp4','video/webm':'webm'};
 const status=t=>$('#studio-status').textContent=t;
 $('#studio-product').innerHTML=products.map(p=>`<option value="${p.slug}">${esc(p.name)}</option>`).join('');
 const slug=()=>$('#studio-product').value;
 function draft(){return drafts[slug()]||(drafts[slug()]={cover:'',media:[]});}
 function render(){const p=products.find(p=>p.slug===slug());$('#studio-title').textContent=p.name;$('#studio-gallery').innerHTML=(draft().media||[]).map((m,i)=>{const src=objectURLs.get(m.url)||m.url;return `<article class="studio-item"><div class="studio-thumb">${m.type==='youtube'?'<span>YouTube video</span>':m.type==='video'?`<video controls preload="metadata" src="${esc(src)}"></video>`:`<img src="${esc(src)}" alt="${esc(m.label)}">`}</div><label>Caption<input data-caption="${i}" value="${esc(m.label)}" maxlength="100"></label><div class="studio-item-actions"><button data-lead="${i}" class="button">${i===0?'Lead media':'Make lead'}</button><button data-remove="${i}" class="button">Remove</button></div></article>`;}).join('')||'<p class="studio-empty">Add the real aircraft exterior, cabin, cockpit and walkthrough. Nothing is uploaded to a server.</p>';$('#studio-total').textContent=`${[...files.values()].reduce((n,f)=>n+f.size,0)/1048576|0} MB of local media`;
 }
 async function addFiles(list){const d=draft();let count=0;for(const f of list){const ext=supported[f.type];if(!ext){status('Unsupported file. Use PNG, JPG, WebP, GIF, AVIF, MP4 or WebM.');continue;}if(f.size>100*1024*1024||[...files.values()].reduce((n,x)=>n+x.size,0)+f.size>200*1024*1024){status('Use files below 100 MB each, and below 200 MB in total. Short compressed clips are recommended.');continue;}const path=`assets/${slug()}/media-${Date.now()}-${++serial}.${ext}`;files.set(path,f);objectURLs.set(path,URL.createObjectURL(f));const type=f.type.startsWith('video/')?'video':ext==='gif'?'clip':'image';d.media.push({type,url:path,label:f.name.replace(/\.[^.]+$/,'').replace(/[_-]+/g,' ').slice(0,100)});if(!d.cover&&type==='image')d.cover=path;count++;}render();if(count)status(`${count} file${count===1?'':'s'} added locally. Export an update ZIP when ready.`);}
 $('#studio-files').addEventListener('change',e=>{addFiles(e.target.files);e.target.value='';});
 const drop=$('#drop-zone');['dragenter','dragover'].forEach(name=>drop.addEventListener(name,e=>{e.preventDefault();drop.classList.add('dragover');}));['dragleave','drop'].forEach(name=>drop.addEventListener(name,e=>{e.preventDefault();drop.classList.remove('dragover');if(name==='drop')addFiles(e.dataTransfer.files);}));
 $('#studio-product').addEventListener('change',render);
 $('#studio-gallery').addEventListener('input',e=>{if(e.target.hasAttribute('data-caption'))draft().media[Number(e.target.dataset.caption)].label=e.target.value.slice(0,100);});
 $('#studio-gallery').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const d=draft();if(b.hasAttribute('data-lead')){const index=Number(b.dataset.lead),m=d.media.splice(index,1)[0];d.media.unshift(m);if(m.type==='image')d.cover=m.url;render();}else if(b.hasAttribute('data-remove')){const m=d.media.splice(Number(b.dataset.remove),1)[0];if(d.cover===m.url)d.cover=d.media.find(x=>x.type==='image')?.url||'';if(files.has(m.url)){files.delete(m.url);URL.revokeObjectURL(objectURLs.get(m.url));objectURLs.delete(m.url);}render();}});
 $('#add-youtube').addEventListener('click',()=>{try{const u=new URL($('#youtube-url').value.trim());if(u.protocol!=='https:'||!['youtu.be','youtube.com','www.youtube.com'].includes(u.hostname))throw Error();const id=u.hostname==='youtu.be'?u.pathname.slice(1):u.searchParams.get('v')||u.pathname.split('/').pop();if(!/^[\w-]{11}$/.test(id||''))throw Error();draft().media.push({type:'youtube',url:`https://www.youtube.com/watch?v=${id}`,label:'Video walkthrough',poster:`https://img.youtube.com/vi/${id}/hqdefault.jpg`});$('#youtube-url').value='';render();status('Video link added.');}catch{status('Enter a valid HTTPS YouTube video URL.');}});
 const enc=new TextEncoder();const table=Uint32Array.from({length:256},(_,n)=>{for(let k=0;k<8;k++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0;});
 function crc32(bytes){let c=0xffffffff;for(const b of bytes)c=table[(c^b)&255]^(c>>>8);return(c^0xffffffff)>>>0;}
 function header(size){const a=new Uint8Array(size);return[a,new DataView(a.buffer)];}
 function zip(entries){const local=[],central=[];let offset=0,total=0;for(const [name,bytes] of entries){const n=enc.encode(name),crc=crc32(bytes);const[a,v]=header(30);v.setUint32(0,0x04034b50,true);v.setUint16(4,20,true);v.setUint16(6,0x800,true);v.setUint32(14,crc,true);v.setUint32(18,bytes.length,true);v.setUint32(22,bytes.length,true);v.setUint16(26,n.length,true);local.push(a,n,bytes);const[c,w]=header(46);w.setUint32(0,0x02014b50,true);w.setUint16(4,20,true);w.setUint16(6,20,true);w.setUint16(8,0x800,true);w.setUint32(16,crc,true);w.setUint32(20,bytes.length,true);w.setUint32(24,bytes.length,true);w.setUint16(28,n.length,true);w.setUint32(42,offset,true);central.push(c,n);offset+=a.length+n.length+bytes.length;total+=c.length+n.length;}const[end,e]=header(22);e.setUint32(0,0x06054b50,true);e.setUint16(8,entries.length,true);e.setUint16(10,entries.length,true);e.setUint32(12,total,true);e.setUint32(16,offset,true);return new Blob([...local,...central,end],{type:'application/zip'});}
 function download(blob,name){const u=URL.createObjectURL(blob);const a=document.createElement('a');a.href=u;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),60000);}
 function overrideJS(data){return 'window.MS_MEDIA_OVERRIDES = '+JSON.stringify(data,null,2).replace(/</g,'\\u003c')+';';}
 function cleanDrafts(){return Object.fromEntries(Object.entries(drafts).filter(([,d])=>d.media?.length||d.cover));}
 $('#export-media').addEventListener('click',async()=>{const b=$('#export-media');b.disabled=true;try{const d=cleanDrafts();if(!Object.keys(d).length)return status('Add media before exporting.');const entries=[['storefront/media-overrides.js',enc.encode(overrideJS(d))]];for(const [path,f] of files)entries.push(['storefront/'+path,new Uint8Array(await f.arrayBuffer())]);entries.push(['READ_ME.txt',enc.encode('This ZIP is a media update, not the full website. Merge its storefront/ folder into the V2 source. It replaces media-overrides.js and adds your media. Rebuild/redeploy the static website to publish. No GitHub or Tebex changes have been made by this editor. Keep your original images and videos. Existing relative media referenced but not uploaded in this editing session must already exist in your source.')]);download(zip(entries),'MikeScripts_Media_Update.zip');status('Media update ZIP created. Your live website has not been changed.');}catch(e){status('Export failed: '+e.message);}finally{b.disabled=false;}});
 const dataURL=f=>new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(Error('Could not read media.'));r.readAsDataURL(f);});
 $('#export-preview').addEventListener('click',async()=>{const b=$('#export-preview');b.disabled=true;try{if(!window.MS_SITE_TEMPLATE)throw Error('Use the supplied standalone Media Studio HTML to build a preview.');const data=JSON.parse(JSON.stringify(cleanDrafts()));for(const d of Object.values(data)){for(const m of d.media||[])if(files.has(m.url)){const old=m.url;m.url=await dataURL(files.get(old));if(d.cover===old)d.cover=m.url;}if(files.has(d.cover))d.cover=await dataURL(files.get(d.cover));}const html=window.MS_SITE_TEMPLATE.replace('window.MS_MEDIA_OVERRIDES = {};',overrideJS(data));download(new Blob([html],{type:'text/html'}),'MikeScripts_With_Your_Media.html');status('Preview created with your local files embedded. External store media and YouTube still need internet.');}catch(e){status(e.message);}finally{b.disabled=false;}});
 render();
})();
